### ISSUE TITLE
Contribute any problems on Recursion

### ISSUE THREAD

**Issue by sourav-122** [sourav-122/hacktoberfest2022#1]

**Comment by soudeepghosh** [comment]
@sourav-122 please assign me this issue

**Comment by sourav-122** [comment]
Assign this issue to you @soudeepghosh

**Comment by sourav-122** [comment]
Assign this issue to you @soudeepghosh

**Comment by Prakash-Mondal** [comment]
Please assign me to solve this issue @sourav-122

**Comment by castbond** [comment]
@sourav-122 Please assign me to solve this issue

**Comment by vipingautam07** [comment]
Please assign me the issue, I will do my best!

**Comment by mit1275** [comment]
Please assign me this issue.

**Comment by srishtig2412** [comment]
please assign this to me

**Comment by pranotip283** [comment]
Pranoti Patil
Can you please assign this to me?

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by Rishi0510** [comment]
Hey! Can you please assign me this under Hacktoberfest? @sourav-122

**Comment by sourav-122** [comment]
Assign this issue @falguni300103 @Rishi0510 @Avy2808 @pranotip283

**Comment by pranotip283** [comment]
I have added the code, can you check?

**Comment by Nansri108** [comment]
hello sir can you please assign to me this issue because i really want to work on this issue.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by riddhitech** [comment]
Sir , I have made a pr , please review.
