### ISSUE TITLE
Maxing an excel spreadsheet in Python

### ISSUE THREAD

**Issue by RitwikGanguly** [sourav-122/hacktoberfest2022#144]
Have to make an excel spreadsheet using python where you can choose your desired cell size

**Comment by RitwikGanguly** [comment]
@sourav-122 can you please assign me in this issue

**Comment by sourav-122** [comment]
assigned U @RitwikGanguly

**Comment by RitwikGanguly** [comment]
@sourav-122 
a new pr is sent at #146

**Comment by RitwikGanguly** [comment]
please review and merge the pr

**Comment by RitwikGanguly** [comment]
one thing
@sourav-122 link my pr in this issue and close the issue

**Comment by RitwikGanguly** [comment]
will you @sourav-122 ??
