### ISSUE TITLE
Contribute any problems on LinkedList 

### ISSUE THREAD

**Issue by sourav-122** [sourav-122/hacktoberfest2022#2]

**Comment by biswajitpat** [comment]
please assign me to do this @sourav-122 sir🙏. i will try my level best to solve the issues.

**Comment by soudeepghosh** [comment]
@sourav-122  please assign me to solve that issue

**Comment by sourav-122** [comment]
Assign this issue to you @biswajitpat

**Comment by prantikdhara** [comment]
@sourav-122 assign me to solve that issue

**Comment by biswajitpat** [comment]
Yes I will create the next file on deletion of ll.

**Comment by Prakash-Mondal** [comment]
Please assign me to solve this issue @sourav-122

**Comment by biswajitpat** [comment]
I have added a new PR on deletion of linked list using python.

**Comment by TechCursed** [comment]
Please assign me to solve this issue

**Comment by sourav-122** [comment]
Assign this issue to you @prantikdhara

**Comment by sourav-122** [comment]
Assign this issue @TechCursed

**Comment by Kushbankey** [comment]
Assign me this issue!

**Comment by TechCursed** [comment]
I'll be contributing on Finding the middle element of a LL

**Comment by vipingautam07** [comment]
Please assign me the issue, I will do my best!

**Comment by shikha-tomar14** [comment]
Please assign me to solve this issue

**Comment by Shalu461975** [comment]
assiign this to me

**Comment by srishtig2412** [comment]
please assign this to me

**Comment by EngineerAditijain** [comment]
Hello sir,
can you  please assign this to me

**Comment by sourav-122** [comment]
Assign this issue @EngineerAditijain

**Comment by pranotip283** [comment]
Can you please assign this issue to me?

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Rishi0510** [comment]
Hey! Can you please assign me this under Hacktoberfest? @sourav-122

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by pranotip283** [comment]
I have added the code, can you please check?

**Comment by Nansri108** [comment]
hello sir can you please assign to me this issue because i really want to work on this issue.

**Comment by riddhitech** [comment]
Please assign me this issue.
