### ISSUE TITLE
Contribute any Problem on Stacks and Queues

### ISSUE THREAD

**Issue by sourav-122** [sourav-122/hacktoberfest2022#3]

**Comment by Prakash-Mondal** [comment]
Please assign me to solve this issue @sourav-122

**Comment by sourav-122** [comment]
yup @biswajitpat

**Comment by vipingautam07** [comment]
Please assign me the issue, I will do my best!

**Comment by shikha-tomar14** [comment]
Please assign me to solve this given issue @sourav-122

**Comment by sourav-122** [comment]
Assign this issue to you @shikha-tomar14

**Comment by Ayashika** [comment]
Please assign me this issue. I want to add solutions to some good problems on stacks and queues.

**Comment by srishtig2412** [comment]
please assign this to me

**Comment by sourav-122** [comment]
Assign this issue @srishtig2412

**Comment by pranotip283** [comment]
Can you please assign this to me?

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Rishi0510** [comment]
Can you please assign me this issue under hacktoberfest ? @sourav-122

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by sourav-122** [comment]
> Can you please assign this issue to me? @sourav-122
