### ISSUE TITLE
Contribute Sliding Window Question on DSA from Leetcode and Gfg

### ISSUE THREAD

**Issue by Khemendra-Bhardwaj** [sourav-122/hacktoberfest2022#34]
Hey please assign me this task.

**Comment by mit1275** [comment]
I want to contribute. Please assign to me.

**Comment by sourav-122** [comment]
Assign this issue @mit1275

**Comment by vipingautam07** [comment]
Please assign me the issue, I will do my best!

**Comment by EngineerAditijain** [comment]
Hello Sir,
please assign me  this task
 i have solved around 400+ problems at leetcode

**Comment by sourav-122** [comment]
Assign this issue @EngineerAditijain

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by Saaraansh10** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Saaraansh10** [comment]
> Can you please assign this issue to me? @sourav-122

Code written

**Comment by Saaraansh10** [comment]
Please merge my pull requests into the main branch.
It is a kind request!!!
