### ISSUE TITLE
Contribute any Graph Algorithms

### ISSUE THREAD

**Issue by sourav-122** [sourav-122/hacktoberfest2022#4]

**Comment by Prakash-Mondal** [comment]
Please assign me to solve this issue @sourav-122

**Comment by NiranjanLangade** [comment]
Hello @sourav-122 !!
I can solve this issue please assign this to me

**Comment by mit1275** [comment]
I want to contribute. Please assign to me @sourav-122 .

**Comment by sourav-122** [comment]
Assign this issue @mit1275

**Comment by shikha-tomar14** [comment]
Please assign me to solve this issue Sir!

**Comment by sourav-122** [comment]
Assign this issue @shikha-tomar14

**Comment by pranotip283** [comment]
Can you please assign this to me?

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by falguni300103** [comment]
Can you please assign this issue to me? @sourav-122

**Comment by Saaraansh10** [comment]
Can you please assign this issue to me @sourav-122 ?

**Comment by Saaraansh10** [comment]
> Can you please assign this issue to me @sourav-122 ?

code added successfully
