### ISSUE TITLE
Contribute any Problem of DSA

### ISSUE THREAD

**Issue by sourav-122** [sourav-122/hacktoberfest2022#7]

**Comment by ayushnandanwar08** [comment]
Hi @sourav-122 Can assign this task to me.
I will try to add few problem solution to this repo.

**Comment by sourav-122** [comment]
Assign this issue to you @ayushnandanwar08

**Comment by Prakash-Mondal** [comment]
Please assign me to solve this issue @sourav-122

**Comment by prantikdhara** [comment]
@sourav-122 assign me this task

**Comment by castbond** [comment]
@sourav-122 Please assign me in this project

**Comment by akash786y** [comment]
Hi sir, please assign me this task

**Comment by sourav-122** [comment]
Assign this issue @akash786y

**Comment by sahil-k95** [comment]
hi sir please assign me the task

**Comment by vipingautam07** [comment]
Please assign me the issue, I will do my best!

**Comment by shikha-tomar14** [comment]
Please assign me to solve this issue

**Comment by sourav-122** [comment]
Assign this issue @shikha-tomar14

**Comment by NileshSinha11** [comment]
please addign this issue to me i would like to add some of my dsa problem solutions

**Comment by NileshSinha11** [comment]
Please assign this issue to me i would like to add some of my dsa problem solution .

**Comment by sourav-122** [comment]
Assign this issue @NileshSinha11

**Comment by RitwikGanguly** [comment]
@sourav-122 can you assign me in this task

**Comment by sourav-122** [comment]
Assigned you @RitwikGanguly

**Comment by RitwikGanguly** [comment]
I wanna contribute in this issue also but I think if you not review and merge my prev pr #146 then both of these prs are considered as one pr

i think this, what's your opinion @sourav-122

**Comment by sourav-122** [comment]
Your thinking is right ..the number of pr depends on how many valid(without spam label) PR are merged by the maintainer @RitwikGanguly

**Comment by RitwikGanguly** [comment]
kindly review and merge my pr of #147 

and please link in this issue

**Comment by pranotip283** [comment]
Can you please assign this to me?

**Comment by keshav-guptaa** [comment]
please assign this issue to me

**Comment by falguni300103** [comment]
Can you please assign this issue to me?

**Comment by Rishi0510** [comment]
Hey! Can you please assign me this under Hacktoberfest? @sourav-122

**Comment by Avy2808** [comment]
@sourav-122  can you please assign this issue to me under hacktober fest 2022 ?

**Comment by pranotip283** [comment]
I have added the code, can you please check?

**Comment by Nansri108** [comment]
hello sir can you please assign to me this issue because i really want to work on this issue.

**Comment by riddhitech** [comment]
Please assign me this issue.
